### ISSUE TITLE
Firefox >= 63 attaches fixed elements to the larger of the ICB or the visual viewport

### ISSUE THREAD

**Issue by theres-waldo** [bokand/bokand.github.io#6]
In Firefox 63, the handling of position:fixed elements was changed so that they're attached to the larger of the ICB or the visual viewport.

This matches the behaviour of Safari, and on most pages (namely, ones where the min-scale size = the ICB size) Chrome.

Filing this issue to track updating the document to reflect this.

**Comment by bokand** [comment]
I've updated it in https://github.com/bokand/bokand.github.io/commit/24bffa36b2e174afdf506f9129bdf301d61d8bbb

Mind taking a look to see if that's accurate?

**Comment by theres-waldo** [comment]
Thanks very much! It looks generally right. I wrote a few comments on the commit.
